### PR TITLE
Ný grein

### PR DESCRIPTION
**Pull request by dhsigurdar**
Geogebra

### CODE REVIEW

**Review by busla — COMMENTED** [review]
removing hoverrole altogether?

**Comment by dhsigurdar** [comment]
Well, I just commented it out. It was giving an error even though I´m not using it anywhere.

-Dorotea

**Comment by busla** [comment]
ok, just checking ☺️

**Review by busla — APPROVED** [review]
LGTM

**Comment by benediktmag** [comment]
hoverrole virtist valda vandræðum á Windows, nkl. sömu skrár með sama environment.yml á linux var ok.

**Comment by busla** [comment]
prófa að reruna jobbið, eh timeout 🤷

**Review by busla — APPROVED** [review]
LGTM

**Review by benediktmag — APPROVED** [review]

**Pull request merged**
